apiVersion: v1
kind: Secret
metadata:
  name: fluent-bit-aws
  namespace: kube-system
type: Opaque
data:
  aws-access-key-id: QUtJQVJBSzNBTUZFSEQ2RFFFT0c=
  aws-secret-access-key: S3ZyTjVHTTFvSGxYYU80RDMwMFJ2Tk94dDBCZ21lRXNqUVI0aHpoSQ==