apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics-container
          image: 069447213384.dkr.ecr.us-east-1.amazonaws.com/coworking-space:latest
          ports:
            - containerPort: 5153
          envFrom:
            - configMapRef:
                name: db-cm-env
            - secretRef:
                name: db-secret-env